# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92f7ca383316e59258188551483c54bbc8960899e6141e546346b962d56cedad6fc6df52fa877b4a4050ced7e63dd7717414f54aa681ced92ca747f495723222

test:
  secret_key_base: 13ddbb6feff2ebf1751fff611cd5b336062fd6db4f9e7f49f249d7bb9e59f03e387107f6257505e9b4e1c3312dad14983c2e3bf05e2c6c68f5e59cc087f46828

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
